import { z } from 'zod';
declare const EnvSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test"]>>;
    PORT: z.ZodDefault<z.ZodNumber>;
    APP_URL: z.ZodString;
    API_URL: z.ZodOptional<z.ZodString>;
    DATABASE_URL: z.ZodString;
    DATABASE_POOL_MAX: z.ZodDefault<z.ZodNumber>;
    REDIS_URL: z.ZodDefault<z.ZodString>;
    REDIS_PASSWORD: z.ZodOptional<z.ZodString>;
    MINIO_ENDPOINT: z.ZodDefault<z.ZodString>;
    MINIO_PORT: z.ZodDefault<z.ZodNumber>;
    MINIO_USE_SSL: z.ZodDefault<z.ZodBoolean>;
    MINIO_ACCESS_KEY: z.ZodString;
    MINIO_SECRET_KEY: z.ZodString;
    MINIO_BUCKET: z.ZodDefault<z.ZodString>;
    MINIO_REGION: z.ZodDefault<z.ZodString>;
    MEILISEARCH_HOST: z.ZodDefault<z.ZodString>;
    MEILISEARCH_API_KEY: z.ZodDefault<z.ZodString>;
    JWT_SECRET: z.ZodString;
    JWT_REFRESH_SECRET: z.ZodString;
    JWT_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    JWT_REFRESH_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    TOTP_ISSUER: z.ZodDefault<z.ZodString>;
    AES_ENCRYPTION_KEY: z.ZodString;
    SMTP_HOST: z.ZodString;
    SMTP_PORT: z.ZodDefault<z.ZodNumber>;
    SMTP_SECURE: z.ZodDefault<z.ZodBoolean>;
    SMTP_USER: z.ZodString;
    SMTP_PASS: z.ZodString;
    EMAIL_FROM: z.ZodString;
    GOOGLE_CLIENT_ID: z.ZodOptional<z.ZodString>;
    GOOGLE_CLIENT_SECRET: z.ZodOptional<z.ZodString>;
    GOOGLE_CALLBACK_URL: z.ZodOptional<z.ZodString>;
    MICROSOFT_CLIENT_ID: z.ZodOptional<z.ZodString>;
    MICROSOFT_CLIENT_SECRET: z.ZodOptional<z.ZodString>;
    MICROSOFT_TENANT_ID: z.ZodDefault<z.ZodString>;
    MICROSOFT_CALLBACK_URL: z.ZodOptional<z.ZodString>;
    LDAP_URL: z.ZodOptional<z.ZodString>;
    LDAP_BIND_DN: z.ZodOptional<z.ZodString>;
    LDAP_BIND_CREDENTIALS: z.ZodOptional<z.ZodString>;
    LDAP_SEARCH_BASE: z.ZodOptional<z.ZodString>;
    LDAP_SEARCH_FILTER: z.ZodDefault<z.ZodString>;
    ZERNIO_API_KEY: z.ZodOptional<z.ZodString>;
    ZERNIO_API_URL: z.ZodOptional<z.ZodString>;
    CLAMAV_SOCKET: z.ZodOptional<z.ZodString>;
    CLAMAV_HOST: z.ZodDefault<z.ZodString>;
    CLAMAV_PORT: z.ZodDefault<z.ZodNumber>;
    RATE_LIMIT_WINDOW_MS: z.ZodDefault<z.ZodNumber>;
    RATE_LIMIT_MAX: z.ZodDefault<z.ZodNumber>;
    AUTH_RATE_LIMIT_MAX: z.ZodDefault<z.ZodNumber>;
    MAX_FILE_SIZE_MB: z.ZodDefault<z.ZodNumber>;
    ALLOWED_MIME_TYPES: z.ZodDefault<z.ZodString>;
    CONNECTOR_SYNC_INTERVAL_MINUTES: z.ZodDefault<z.ZodNumber>;
    CONNECTOR_MAX_RETRIES: z.ZodDefault<z.ZodNumber>;
    STRIPE_SECRET_KEY: z.ZodOptional<z.ZodString>;
    STRIPE_PUBLISHABLE_KEY: z.ZodOptional<z.ZodString>;
    STRIPE_WEBHOOK_SECRET: z.ZodOptional<z.ZodString>;
    ANTHROPIC_API_KEY: z.ZodOptional<z.ZodString>;
    BUNNY_CDN_API_KEY: z.ZodOptional<z.ZodString>;
    BUNNY_CDN_STORAGE_ZONE: z.ZodOptional<z.ZodString>;
    MUXDATA_TOKEN_ID: z.ZodOptional<z.ZodString>;
    MUXDATA_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    ZOOM_API_KEY: z.ZodOptional<z.ZodString>;
    ZOOM_API_SECRET: z.ZodOptional<z.ZodString>;
    DAILY_CO_API_KEY: z.ZodOptional<z.ZodString>;
    PUPPETEER_EXECUTABLE_PATH: z.ZodOptional<z.ZodString>;
    LMS_BASE_URL: z.ZodOptional<z.ZodString>;
    CERTIFICATE_ISSUER: z.ZodDefault<z.ZodString>;
    MAX_UPLOAD_SIZE_MB: z.ZodDefault<z.ZodNumber>;
    SCORM_STORAGE_BUCKET: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "production" | "test";
    PORT: number;
    APP_URL: string;
    DATABASE_URL: string;
    DATABASE_POOL_MAX: number;
    REDIS_URL: string;
    MINIO_ENDPOINT: string;
    MINIO_PORT: number;
    MINIO_USE_SSL: boolean;
    MINIO_ACCESS_KEY: string;
    MINIO_SECRET_KEY: string;
    MINIO_BUCKET: string;
    MINIO_REGION: string;
    MEILISEARCH_HOST: string;
    MEILISEARCH_API_KEY: string;
    JWT_SECRET: string;
    JWT_REFRESH_SECRET: string;
    JWT_EXPIRES_IN: string;
    JWT_REFRESH_EXPIRES_IN: string;
    TOTP_ISSUER: string;
    AES_ENCRYPTION_KEY: string;
    SMTP_HOST: string;
    SMTP_PORT: number;
    SMTP_SECURE: boolean;
    SMTP_USER: string;
    SMTP_PASS: string;
    EMAIL_FROM: string;
    MICROSOFT_TENANT_ID: string;
    LDAP_SEARCH_FILTER: string;
    CLAMAV_HOST: string;
    CLAMAV_PORT: number;
    RATE_LIMIT_WINDOW_MS: number;
    RATE_LIMIT_MAX: number;
    AUTH_RATE_LIMIT_MAX: number;
    MAX_FILE_SIZE_MB: number;
    ALLOWED_MIME_TYPES: string;
    CONNECTOR_SYNC_INTERVAL_MINUTES: number;
    CONNECTOR_MAX_RETRIES: number;
    CERTIFICATE_ISSUER: string;
    MAX_UPLOAD_SIZE_MB: number;
    SCORM_STORAGE_BUCKET: string;
    API_URL?: string | undefined;
    REDIS_PASSWORD?: string | undefined;
    GOOGLE_CLIENT_ID?: string | undefined;
    GOOGLE_CLIENT_SECRET?: string | undefined;
    GOOGLE_CALLBACK_URL?: string | undefined;
    MICROSOFT_CLIENT_ID?: string | undefined;
    MICROSOFT_CLIENT_SECRET?: string | undefined;
    MICROSOFT_CALLBACK_URL?: string | undefined;
    LDAP_URL?: string | undefined;
    LDAP_BIND_DN?: string | undefined;
    LDAP_BIND_CREDENTIALS?: string | undefined;
    LDAP_SEARCH_BASE?: string | undefined;
    ZERNIO_API_KEY?: string | undefined;
    ZERNIO_API_URL?: string | undefined;
    CLAMAV_SOCKET?: string | undefined;
    STRIPE_SECRET_KEY?: string | undefined;
    STRIPE_PUBLISHABLE_KEY?: string | undefined;
    STRIPE_WEBHOOK_SECRET?: string | undefined;
    ANTHROPIC_API_KEY?: string | undefined;
    BUNNY_CDN_API_KEY?: string | undefined;
    BUNNY_CDN_STORAGE_ZONE?: string | undefined;
    MUXDATA_TOKEN_ID?: string | undefined;
    MUXDATA_TOKEN_SECRET?: string | undefined;
    ZOOM_API_KEY?: string | undefined;
    ZOOM_API_SECRET?: string | undefined;
    DAILY_CO_API_KEY?: string | undefined;
    PUPPETEER_EXECUTABLE_PATH?: string | undefined;
    LMS_BASE_URL?: string | undefined;
}, {
    APP_URL: string;
    DATABASE_URL: string;
    MINIO_ACCESS_KEY: string;
    MINIO_SECRET_KEY: string;
    JWT_SECRET: string;
    JWT_REFRESH_SECRET: string;
    AES_ENCRYPTION_KEY: string;
    SMTP_HOST: string;
    SMTP_USER: string;
    SMTP_PASS: string;
    EMAIL_FROM: string;
    NODE_ENV?: "development" | "production" | "test" | undefined;
    PORT?: number | undefined;
    API_URL?: string | undefined;
    DATABASE_POOL_MAX?: number | undefined;
    REDIS_URL?: string | undefined;
    REDIS_PASSWORD?: string | undefined;
    MINIO_ENDPOINT?: string | undefined;
    MINIO_PORT?: number | undefined;
    MINIO_USE_SSL?: boolean | undefined;
    MINIO_BUCKET?: string | undefined;
    MINIO_REGION?: string | undefined;
    MEILISEARCH_HOST?: string | undefined;
    MEILISEARCH_API_KEY?: string | undefined;
    JWT_EXPIRES_IN?: string | undefined;
    JWT_REFRESH_EXPIRES_IN?: string | undefined;
    TOTP_ISSUER?: string | undefined;
    SMTP_PORT?: number | undefined;
    SMTP_SECURE?: boolean | undefined;
    GOOGLE_CLIENT_ID?: string | undefined;
    GOOGLE_CLIENT_SECRET?: string | undefined;
    GOOGLE_CALLBACK_URL?: string | undefined;
    MICROSOFT_CLIENT_ID?: string | undefined;
    MICROSOFT_CLIENT_SECRET?: string | undefined;
    MICROSOFT_TENANT_ID?: string | undefined;
    MICROSOFT_CALLBACK_URL?: string | undefined;
    LDAP_URL?: string | undefined;
    LDAP_BIND_DN?: string | undefined;
    LDAP_BIND_CREDENTIALS?: string | undefined;
    LDAP_SEARCH_BASE?: string | undefined;
    LDAP_SEARCH_FILTER?: string | undefined;
    ZERNIO_API_KEY?: string | undefined;
    ZERNIO_API_URL?: string | undefined;
    CLAMAV_SOCKET?: string | undefined;
    CLAMAV_HOST?: string | undefined;
    CLAMAV_PORT?: number | undefined;
    RATE_LIMIT_WINDOW_MS?: number | undefined;
    RATE_LIMIT_MAX?: number | undefined;
    AUTH_RATE_LIMIT_MAX?: number | undefined;
    MAX_FILE_SIZE_MB?: number | undefined;
    ALLOWED_MIME_TYPES?: string | undefined;
    CONNECTOR_SYNC_INTERVAL_MINUTES?: number | undefined;
    CONNECTOR_MAX_RETRIES?: number | undefined;
    STRIPE_SECRET_KEY?: string | undefined;
    STRIPE_PUBLISHABLE_KEY?: string | undefined;
    STRIPE_WEBHOOK_SECRET?: string | undefined;
    ANTHROPIC_API_KEY?: string | undefined;
    BUNNY_CDN_API_KEY?: string | undefined;
    BUNNY_CDN_STORAGE_ZONE?: string | undefined;
    MUXDATA_TOKEN_ID?: string | undefined;
    MUXDATA_TOKEN_SECRET?: string | undefined;
    ZOOM_API_KEY?: string | undefined;
    ZOOM_API_SECRET?: string | undefined;
    DAILY_CO_API_KEY?: string | undefined;
    PUPPETEER_EXECUTABLE_PATH?: string | undefined;
    LMS_BASE_URL?: string | undefined;
    CERTIFICATE_ISSUER?: string | undefined;
    MAX_UPLOAD_SIZE_MB?: number | undefined;
    SCORM_STORAGE_BUCKET?: string | undefined;
}>;
export declare const env: {
    NODE_ENV: "development" | "production" | "test";
    PORT: number;
    APP_URL: string;
    DATABASE_URL: string;
    DATABASE_POOL_MAX: number;
    REDIS_URL: string;
    MINIO_ENDPOINT: string;
    MINIO_PORT: number;
    MINIO_USE_SSL: boolean;
    MINIO_ACCESS_KEY: string;
    MINIO_SECRET_KEY: string;
    MINIO_BUCKET: string;
    MINIO_REGION: string;
    MEILISEARCH_HOST: string;
    MEILISEARCH_API_KEY: string;
    JWT_SECRET: string;
    JWT_REFRESH_SECRET: string;
    JWT_EXPIRES_IN: string;
    JWT_REFRESH_EXPIRES_IN: string;
    TOTP_ISSUER: string;
    AES_ENCRYPTION_KEY: string;
    SMTP_HOST: string;
    SMTP_PORT: number;
    SMTP_SECURE: boolean;
    SMTP_USER: string;
    SMTP_PASS: string;
    EMAIL_FROM: string;
    MICROSOFT_TENANT_ID: string;
    LDAP_SEARCH_FILTER: string;
    CLAMAV_HOST: string;
    CLAMAV_PORT: number;
    RATE_LIMIT_WINDOW_MS: number;
    RATE_LIMIT_MAX: number;
    AUTH_RATE_LIMIT_MAX: number;
    MAX_FILE_SIZE_MB: number;
    ALLOWED_MIME_TYPES: string;
    CONNECTOR_SYNC_INTERVAL_MINUTES: number;
    CONNECTOR_MAX_RETRIES: number;
    CERTIFICATE_ISSUER: string;
    MAX_UPLOAD_SIZE_MB: number;
    SCORM_STORAGE_BUCKET: string;
    API_URL?: string | undefined;
    REDIS_PASSWORD?: string | undefined;
    GOOGLE_CLIENT_ID?: string | undefined;
    GOOGLE_CLIENT_SECRET?: string | undefined;
    GOOGLE_CALLBACK_URL?: string | undefined;
    MICROSOFT_CLIENT_ID?: string | undefined;
    MICROSOFT_CLIENT_SECRET?: string | undefined;
    MICROSOFT_CALLBACK_URL?: string | undefined;
    LDAP_URL?: string | undefined;
    LDAP_BIND_DN?: string | undefined;
    LDAP_BIND_CREDENTIALS?: string | undefined;
    LDAP_SEARCH_BASE?: string | undefined;
    ZERNIO_API_KEY?: string | undefined;
    ZERNIO_API_URL?: string | undefined;
    CLAMAV_SOCKET?: string | undefined;
    STRIPE_SECRET_KEY?: string | undefined;
    STRIPE_PUBLISHABLE_KEY?: string | undefined;
    STRIPE_WEBHOOK_SECRET?: string | undefined;
    ANTHROPIC_API_KEY?: string | undefined;
    BUNNY_CDN_API_KEY?: string | undefined;
    BUNNY_CDN_STORAGE_ZONE?: string | undefined;
    MUXDATA_TOKEN_ID?: string | undefined;
    MUXDATA_TOKEN_SECRET?: string | undefined;
    ZOOM_API_KEY?: string | undefined;
    ZOOM_API_SECRET?: string | undefined;
    DAILY_CO_API_KEY?: string | undefined;
    PUPPETEER_EXECUTABLE_PATH?: string | undefined;
    LMS_BASE_URL?: string | undefined;
};
export type Env = z.infer<typeof EnvSchema>;
export {};
//# sourceMappingURL=env.d.ts.map