"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.fileRouter = void 0;
const express_1 = require("express");
const file_controller_1 = require("../controllers/file.controller");
const auth_middleware_1 = require("../middleware/auth.middleware");
const upload_middleware_1 = require("../middleware/upload.middleware");
const virusScan_middleware_1 = require("../middleware/virusScan.middleware");
const rateLimit_middleware_1 = require("../middleware/rateLimit.middleware");
const audit_middleware_1 = require("../middleware/audit.middleware");
const router = (0, express_1.Router)();
exports.fileRouter = router;
router.use(auth_middleware_1.authMiddleware);
router.get('/', (req, res) => file_controller_1.fileController.listFiles(req, res));
router.get('/recycle-bin', (req, res) => file_controller_1.fileController.recycleBin(req, res));
router.get('/starred', (req, res) => file_controller_1.fileController.listFiles(req, res));
router.post('/upload', rateLimit_middleware_1.uploadRateLimit, upload_middleware_1.uploadSingle, virusScan_middleware_1.virusScanMiddleware, (0, audit_middleware_1.auditLog)({ action: 'file.upload', resourceType: 'file', getResourceId: (req) => req.file?.originalname ?? 'unknown' }), (req, res) => file_controller_1.fileController.upload(req, res));
router.post('/bulk', (0, audit_middleware_1.auditLog)({ action: 'file.bulk', resourceType: 'file' }), (req, res) => file_controller_1.fileController.bulkOperation(req, res));
router.get('/:id', (req, res) => file_controller_1.fileController.getFile(req, res));
router.get('/:id/download', (req, res) => file_controller_1.fileController.download(req, res));
router.get('/:id/preview', (req, res) => file_controller_1.fileController.preview(req, res));
router.put('/:id', (0, audit_middleware_1.auditLog)({ action: 'file.update', resourceType: 'file' }), (req, res) => file_controller_1.fileController.updateFile(req, res));
router.delete('/:id', (0, audit_middleware_1.auditLog)({ action: 'file.delete', resourceType: 'file' }), (req, res) => file_controller_1.fileController.deleteFile(req, res));
router.post('/:id/restore', (req, res) => file_controller_1.fileController.restoreFile(req, res));
router.delete('/:id/permanent', (0, audit_middleware_1.auditLog)({ action: 'file.permanent_delete', resourceType: 'file' }), (req, res) => file_controller_1.fileController.permanentDelete(req, res));
router.post('/:id/star', (req, res) => file_controller_1.fileController.toggleStar(req, res));
router.get('/:id/versions', (req, res) => file_controller_1.fileController.listVersions(req, res));
router.post('/:id/version', rateLimit_middleware_1.uploadRateLimit, upload_middleware_1.uploadSingle, virusScan_middleware_1.virusScanMiddleware, (req, res) => file_controller_1.fileController.uploadVersion(req, res));
router.get('/:id/versions/:versionId/restore', (req, res) => file_controller_1.fileController.restoreVersion(req, res));
//# sourceMappingURL=file.routes.js.map