"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.workspaceRouter = void 0;
const express_1 = require("express");
const workspace_controller_1 = require("../controllers/workspace.controller");
const auth_middleware_1 = require("../middleware/auth.middleware");
const rbac_middleware_1 = require("../middleware/rbac.middleware");
const router = (0, express_1.Router)();
exports.workspaceRouter = router;
router.use(auth_middleware_1.authMiddleware);
router.post('/', (req, res) => workspace_controller_1.workspaceController.create(req, res));
router.get('/', (req, res) => workspace_controller_1.workspaceController.list(req, res));
router.get('/:id', (0, rbac_middleware_1.requireWorkspaceMembership)(), (req, res) => workspace_controller_1.workspaceController.get(req, res));
router.put('/:id', (0, rbac_middleware_1.requireWorkspaceAdmin)(), (req, res) => workspace_controller_1.workspaceController.update(req, res));
router.delete('/:id', (0, rbac_middleware_1.requireWorkspaceAdmin)(), (req, res) => workspace_controller_1.workspaceController.remove(req, res));
router.post('/:id/members', (0, rbac_middleware_1.requireWorkspaceAdmin)(), (req, res) => workspace_controller_1.workspaceController.inviteMember(req, res));
router.put('/:id/members/:userId', (0, rbac_middleware_1.requireWorkspaceAdmin)(), (req, res) => workspace_controller_1.workspaceController.updateMember(req, res));
router.delete('/:id/members/:userId', (0, rbac_middleware_1.requireWorkspaceAdmin)(), (req, res) => workspace_controller_1.workspaceController.removeMember(req, res));
router.get('/:id/activity', (0, rbac_middleware_1.requireWorkspaceMembership)(), (req, res) => workspace_controller_1.workspaceController.getActivity(req, res));
router.get('/:id/files', (0, rbac_middleware_1.requireWorkspaceMembership)(), (req, res) => workspace_controller_1.workspaceController.getFiles(req, res));
//# sourceMappingURL=workspace.routes.js.map