import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = { title: 'Privacy Policy · Lamid FileShare' };

const LAST_UPDATED = 'May 27, 2026';

const sections = [
  {
    title: '1. Information We Collect',
    body: `We collect information you provide directly (name, email, password, profile details, payment information), information generated by your use of the Platform (course progress, quiz results, certificates, XP, badges, login timestamps, IP address, device type), and information from third-party services if you sign in via Google or Microsoft OAuth.`,
  },
  {
    title: '2. How We Use Your Information',
    body: `We use your information to: provide, maintain, and improve the Platform; personalise your learning experience and course recommendations; process payments and issue certificates; send transactional emails (receipts, password resets, certificate issuance) and, if you opt in, learning digests and product updates; enforce our Terms of Service; comply with legal obligations; and generate anonymised aggregate analytics.`,
  },
  {
    title: '3. Data Sharing',
    body: `We do not sell your personal data. We share data only with: (a) trusted service providers who process data on our behalf under strict confidentiality agreements (Stripe for payments, AWS for hosting, Resend for email, Mux for video); (b) instructors of courses you are enrolled in, limited to your name and progress data; (c) your organisation administrator, if you access Lamid FileShare through an enterprise account; and (d) law enforcement or regulators when required by law.`,
  },
  {
    title: '4. Cookies and Tracking',
    body: `We use strictly necessary cookies for authentication and security, functional cookies to remember your preferences, and analytics cookies (anonymised) to understand how the Platform is used. You can control non-essential cookies through your browser settings. We do not use advertising or cross-site tracking cookies.`,
  },
  {
    title: '5. Data Retention',
    body: `We retain your account data for as long as your account is active. Course progress and certificates are retained for the lifetime of your account. If you delete your account, we delete your personal data within 30 days, except where we are required to retain it for legal or tax compliance purposes (typically 7 years for financial records).`,
  },
  {
    title: '6. Your Rights',
    body: `Depending on your location, you may have the right to: access the personal data we hold about you; correct inaccurate data; request deletion of your data ("right to be forgotten"); export your data in a portable format; object to certain processing; and withdraw consent where processing is based on consent. To exercise these rights, email privacy@lamidgroup.com. We will respond within 30 days.`,
  },
  {
    title: '7. Security',
    body: `We implement industry-standard security measures including TLS encryption in transit, AES-256 encryption at rest, bcrypt password hashing, two-factor authentication, and regular security audits. No method of transmission over the internet is 100% secure; we cannot guarantee absolute security but are committed to protecting your data.`,
  },
  {
    title: '8. Children\'s Privacy',
    body: `Lamid FileShare is not directed at children under 13 years of age. We do not knowingly collect personal information from children under 13. If you believe a child has provided us with personal information, please contact us immediately and we will delete it.`,
  },
  {
    title: '9. International Transfers',
    body: `Your data may be transferred to and processed in countries other than your own. Where we transfer data outside the EEA or UK, we ensure appropriate safeguards are in place, such as Standard Contractual Clauses approved by the European Commission.`,
  },
  {
    title: '10. Changes to This Policy',
    body: `We may update this Privacy Policy from time to time. Material changes will be communicated via email or a prominent notice on the Platform. Your continued use of the Platform after changes take effect constitutes acceptance of the updated policy.`,
  },
  {
    title: '11. Contact Us',
    body: `For privacy-related questions or to exercise your rights, contact our Data Protection Officer at privacy@lamidgroup.com. For urgent security concerns, email security@lamidgroup.com. Postal address: Lamid FileShare Privacy, 123 Learning Lane, Tech City, TC 10001.`,
  },
];

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-brand-white-off">
      <header className="bg-white border-b border-brand-gray px-6 py-4 flex items-center justify-between">
        <Link href="/" className="flex items-center gap-2.5 group">
          <div className="w-8 h-8 bg-brand-black rounded-lg flex items-center justify-center transition-transform group-hover:scale-105">
            <div className="w-3 h-3 bg-brand-red rounded-sm" />
          </div>
          <span className="font-bold text-brand-black tracking-tight">Lamid FileShare</span>
        </Link>
        <Link href="/dashboard" className="text-sm text-brand-gray-dark hover:text-brand-black transition-colors">
          Back to app →
        </Link>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <div className="mb-10">
          <h1 className="text-3xl font-black text-brand-black mb-2">Privacy Policy</h1>
          <p className="text-sm text-brand-gray-dark">Last updated: {LAST_UPDATED}</p>
        </div>

        <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 mb-10 text-sm text-blue-800">
          <strong>Your data, your control.</strong> We collect only what we need, never sell your data, and give you full access to export or delete it at any time.
        </div>

        <div className="space-y-8">
          {sections.map((s) => (
            <section key={s.title}>
              <h2 className="text-base font-bold text-brand-black mb-2">{s.title}</h2>
              <p className="text-sm text-brand-gray-dark leading-relaxed">{s.body}</p>
            </section>
          ))}
        </div>

        <div className="mt-12 pt-8 border-t border-brand-gray flex flex-col sm:flex-row gap-4 items-center justify-between">
          <p className="text-xs text-brand-gray-dark">
            Questions? Email <a href="mailto:privacy@lamidgroup.com" className="text-brand-red hover:underline">privacy@lamidgroup.com</a>
          </p>
          <div className="flex gap-4 text-xs">
            <Link href="/terms" className="text-brand-red hover:underline font-medium">Terms of Service</Link>
            <Link href="/dashboard" className="text-brand-gray-dark hover:text-brand-black">Back to app</Link>
          </div>
        </div>
      </main>
    </div>
  );
}
